const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  logActivity: (event, details) => ipcRenderer.invoke('db:logActivity', event, details),
  savePrayer: (content, verseRef) => ipcRenderer.invoke('db:savePrayer', content, verseRef),
  getPrayers: () => ipcRenderer.invoke('db:getPrayers'),
  deletePrayer: (id) => ipcRenderer.invoke('db:deletePrayer', id),
  saveNote: (title, content, book, chapter, verse) => ipcRenderer.invoke('db:saveNote', title, content, book, chapter, verse),
  getNotes: () => ipcRenderer.invoke('db:getNotes'),
  deleteNote: (id) => ipcRenderer.invoke('db:deleteNote', id),
  updateNote: (id, title, content) => ipcRenderer.invoke('db:updateNote', id, title, content),
  saveBookmark: (book, chapter, verse, text) => ipcRenderer.invoke('db:saveBookmark', book, chapter, verse, text),
  getBookmarks: () => ipcRenderer.invoke('db:getBookmarks'),
  isBookmarked: (book, chapter, verse) => ipcRenderer.invoke('db:isBookmarked', book, chapter, verse),
  saveQuizResult: (date, score, total, spiritualTemp, answers) => ipcRenderer.invoke('db:saveQuizResult', date, score, total, spiritualTemp, answers),
  getQuizResults: () => ipcRenderer.invoke('db:getQuizResults'),
  getTodayQuiz: (date) => ipcRenderer.invoke('db:getTodayQuiz', date),
  markVerseSeen: (book, chapter, verse) => ipcRenderer.invoke('db:markVerseSeen', book, chapter, verse),
  getSeenVerses: () => ipcRenderer.invoke('db:getSeenVerses'),
  logReading: (book, chapter, verse, duration) => ipcRenderer.invoke('db:logReading', book, chapter, verse, duration),
  getReadingHistory: (limit) => ipcRenderer.invoke('db:getReadingHistory', limit),
  getStats: () => ipcRenderer.invoke('db:getStats'),
  getReadingCountsByDate: (days) => ipcRenderer.invoke('db:getReadingCountsByDate', days),
  getWeeklyPattern: () => ipcRenderer.invoke('db:getWeeklyPattern'),
  getMonthlyStats: () => ipcRenderer.invoke('db:getMonthlyStats'),
  getPrayerCountsByDate: (days) => ipcRenderer.invoke('db:getPrayerCountsByDate', days),
  getMostReadBooks: () => ipcRenderer.invoke('db:getMostReadBooks'),
  getUnseenVersesByBook: (book, limit) => ipcRenderer.invoke('db:getUnseenVersesByBook', book, limit),
  getProfile: (key) => ipcRenderer.invoke('db:getProfile', key),
  setProfile: (key, value) => ipcRenderer.invoke('db:setProfile', key, value),
  logDailyVerse: (date, book, chapter, verse) => ipcRenderer.invoke('db:logDailyVerse', date, book, chapter, verse),
  getLessons: () => ipcRenderer.invoke('db:getLessons'),
  saveLesson: (title, content, verses) => ipcRenderer.invoke('db:saveLesson', title, content, verses),
  completeLesson: (id) => ipcRenderer.invoke('db:completeLesson', id),
  deleteLesson: (id) => ipcRenderer.invoke('db:deleteLesson', id),
  getVerse: (book, chapter, verse) => ipcRenderer.invoke('bible:getVerse', book, chapter, verse),
  getChapter: (book, chapter) => ipcRenderer.invoke('bible:getChapter', book, chapter),
  getVerses: (book, chapter, start, end) => ipcRenderer.invoke('bible:getVerses', book, chapter, start, end),
  getBookNames: () => ipcRenderer.invoke('bible:getBookNames'),
  getChaptersForBook: (book) => ipcRenderer.invoke('bible:getChaptersForBook', book),
  getVersesForChapter: (book, chapter) => ipcRenderer.invoke('bible:getVersesForChapter', book, chapter),
  getRandomUnseenVerse: (limit) => ipcRenderer.invoke('bible:getRandomUnseenVerse', limit),
  getPersonalizedVerses: (limit) => ipcRenderer.invoke('bible:getPersonalizedVerses', limit),
  getKeyVersesForTopic: (topic) => ipcRenderer.invoke('bible:getKeyVersesForTopic', topic),
  searchVerses: (query, limit) => ipcRenderer.invoke('bible:searchVerses', query, limit),
  getBibleStatus: () => ipcRenderer.invoke('bible:getBibleStatus'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  fetchTranscript: (code) => ipcRenderer.invoke('app:fetchTranscript', code),
  lookupChurchagesUrl: (code) => ipcRenderer.invoke('app:lookupChurchagesUrl', code),
  getCachedSermonTexts: () => ipcRenderer.invoke('app:getCachedSermonTexts'),
  getRecentActivity: (eventType, limit) => ipcRenderer.invoke('app:getRecentActivity', eventType, limit),

  onBibleNotLoaded: (cb) => ipcRenderer.on('bible:not-loaded', () => cb()),
  onBibleLoaded: (cb) => ipcRenderer.on('bible:loaded', () => cb()),
  onBibleVersionReady: (cb) => ipcRenderer.on('bible:version-ready', (e, v) => cb(v)),
  setBibleVersion: (version) => ipcRenderer.invoke('bible:setVersion', version),
  minimizeWindow: () => ipcRenderer.send('window:minimize'),
  maximizeWindow: () => ipcRenderer.send('window:maximize'),
  closeWindow: () => ipcRenderer.send('window:close'),
});
